# Opdracht 2: Vrije opdracht

## Gekozen skill: R Shiny

Voor de vrije opdracht heb ik gekozen om te leren werken met R Shiny. Met R Shiny kunnen interactieve webapplicaties worden gemaakt vanuit R. In plaats van alleen statische grafieken of tabellen te tonen, kan een gebruiker zelf keuzes maken, bijvoorbeeld door een variabele, groep of meetmoment te selecteren. De resultaten worden daarna automatisch aangepast in de applicatie.

Deze skill sluit aan bij mijn toekomstplannen. Mijn stage wil ik bij een consultancy bedrijf in Barcalona gaan lopen. Bas gaf mij de goede tip om dan te kijken naar R shiny. Dit heb ik gedaan en het stage bedrijf is ook super enthousiast dat ik me hier meer in ga verdiepen. Dit komt omdat binnen deze stage het belangrijk is om analyses niet alleen technisch goed uit te voeren, maar de resultaten ook begrijpelijk te presenteren aan mensen die niet dagelijks met R werken. Een interactieve applicatie kan daarbij helpen, omdat gebruikers zelf gegevens kunnen selecteren en resultaten overzichtelijk kunnen bekijken.

Daarnaast sluit R Shiny goed aan bij de cursus. Tijdens mijn project leer ik dit niet maar sommige andere wel. Hierdoor ga ik goed leren hoe ik de resultaten van een analyse interactief en toegankelijk kan presenteren.

## Doel van de opdracht

Het doel van mijn vrije opdracht is om een eigen interactieve R Shiny-applicatie te ontwikkelen waarin biologische data kunnen worden verkregen. De applicatie moet er voor zorgen dat gebruikers zelf een selectie kunnen maken en er vervolgens automatisch passende grafieken en/of samenvattingen worden weergegeven.

Met deze opdracht wil ik leren:

- hoe een Shiny-app is opgebouwd
- hoe gebruikersinput gekoppeld kan worden aan een dataset
- hoe grafieken en resultaten automatisch veranderen op basis van de gekozen input
- hoe biologische data op een overzichtelijke en interactieve manier gepresenteerd kunnen worden

## Planning

- Bedenken waar ik me in wil verdiepen voor de vrije opdracht --> 2 uur
- Er achter komen wat R Shiny exact is en welke biologische dataset geschikt is --> 3 uur
- Les volgen die in de projecticum reader staat voor het eerst begrip --> 3 uur
- Bepalen wat ik voor mijn eigen applicatie nodig heb --> 3 uur 
- Data voorbereiden en controleren --> 4 uur 
- De applicatie bouwen --> 10 uur 
- Testen of verschillende selecties werken en de foute oplossen --> 4 uur 
- Portofolio bijwerken en de resultaten zichtbaar maken --> 4 uur



## Geplande uitwerking

## Geplande uitwerking

Als uitwerking van mijn vrije opdracht maak ik een interactieve R Shiny-applicatie waarin een gebruiker een geneesmiddel kan selecteren. De applicatie laat dan vervolgens zien hoe kankercellen reageren op verschillende concentraties van dat bepaalde geneesmiddel. Hiervoor wil ik gebruikmaken van geneesmiddeldata uit de Genomics of Drug Sensitivity in Cancer-dataset.

De GDSC-dataset bevat gegevens over de gevoeligheid van verschillende kankercellijnen voor anti-kankergeneesmiddelen. Daarom is deze dataset goed voor mijn applicatie.

In de applicatie wil ik de volgende onderdelen gaan proberen te verwerken:

- een keuzemenu waarin de gebruiker een geneesmiddel selecteert
- een grafiek waarin de respons van cellen op het gekozen geneesmiddel zichtbaar is gemaakt
- een korte toelichting bij de resultaten



## Uitwerking van de applicatie

*Dit onderdeel wordt aangevuld nadat de Shiny-applicatie is gebouwd en getest.*
